/************
   DISTANCES_PORTO populate
************/

INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Amarante', 'Baião', 10);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Baião', 'Amarante', 10);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Amarante', 'Felgueiras', 10);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Felgueiras', 'Amarante', 10);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Amarante', 'Gondomar', 30);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Gondomar', 'Amarante', 30);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Amarante', 'Lousada', 20);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Lousada', 'Amarante', 20);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Amarante', 'Maia', 50);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Maia', 'Amarante', 50);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Amarante', 'Marco de Canaveses', 10);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Marco de Canaveses', 'Amarante', 10);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Amarante', 'Matosinhos', 50);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Matosinhos', 'Amarante', 50);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Amarante', 'Paços de Ferreira', 30);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Paços de Ferreira', 'Amarante', 30);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Amarante', 'Paredes', 20);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Paredes', 'Amarante', 20);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Amarante', 'Penafiel', 20);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Penafiel', 'Amarante', 20);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Amarante', 'Porto', 40);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Porto', 'Amarante', 40);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Amarante', 'Póvoa de Varzim', 50);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Póvoa de Varzim', 'Amarante', 50);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Amarante', 'Santo Tirso', 40);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Santo Tirso', 'Amarante', 40);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Amarante', 'Trofa', 50);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Trofa', 'Amarante', 50);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Amarante', 'Valongo', 30);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Valongo', 'Amarante', 30);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Amarante', 'Vila do Conde', 60);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Vila do Conde', 'Amarante', 60);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Amarante', 'Vila Nova de Gaia', 40);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Vila Nova de Gaia', 'Amarante', 40);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Baião', 'Felgueiras', 20);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Felgueiras', 'Baião', 20);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Baião', 'Gondomar', 40);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Gondomar', 'Baião', 40);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Baião', 'Lousada', 30);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Lousada', 'Baião', 30);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Baião', 'Maia', 60);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Maia', 'Baião', 60);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Baião', 'Marco de Canaveses', 10);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Marco de Canaveses', 'Baião', 10);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Baião', 'Matosinhos', 60);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Matosinhos', 'Baião', 60);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Baião', 'Paços de Ferreira', 40);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Paços de Ferreira', 'Baião', 40);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Baião', 'Paredes', 30);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Paredes', 'Baião', 30);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Baião', 'Penafiel', 20);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Penafiel', 'Baião', 20);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Baião', 'Porto', 50);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Porto', 'Baião', 50);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Baião', 'Póvoa de Varzim', 60);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Póvoa de Varzim', 'Baião', 60);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Baião', 'Santo Tirso', 50);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Santo Tirso', 'Baião', 50);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Baião', 'Trofa', 60);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Trofa', 'Baião', 60);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Baião', 'Valongo', 40);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Valongo', 'Baião', 40);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Baião', 'Vila do Conde', 70);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Vila do Conde', 'Baião', 70);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Baião', 'Vila Nova de Gaia', 50);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Vila Nova de Gaia', 'Baião', 50);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Felgueiras', 'Gondomar', 20);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Gondomar', 'Felgueiras', 20);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Felgueiras', 'Lousada', 10);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Lousada', 'Felgueiras', 10);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Felgueiras', 'Maia', 40);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Maia', 'Felgueiras', 40);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Felgueiras', 'Marco de Canaveses', 20);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Marco de Canaveses', 'Felgueiras', 20);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Felgueiras', 'Matosinhos', 40);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Matosinhos', 'Felgueiras', 40);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Felgueiras', 'Paços de Ferreira', 20);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Paços de Ferreira', 'Felgueiras', 20);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Felgueiras', 'Paredes', 10);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Paredes', 'Felgueiras', 10);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Felgueiras', 'Penafiel', 20);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Penafiel', 'Felgueiras', 20);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Felgueiras', 'Porto', 30);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Porto', 'Felgueiras', 30);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Felgueiras', 'Póvoa de Varzim', 40);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Póvoa de Varzim', 'Felgueiras', 40);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Felgueiras', 'Santo Tirso', 30);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Santo Tirso', 'Felgueiras', 30);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Felgueiras', 'Trofa', 40);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Trofa', 'Felgueiras', 40);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Felgueiras', 'Valongo', 20);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Valongo', 'Felgueiras', 20);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Felgueiras', 'Vila do Conde', 50);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Vila do Conde', 'Felgueiras', 50);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Felgueiras', 'Vila Nova de Gaia', 30);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Vila Nova de Gaia', 'Felgueiras', 30);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Gondomar', 'Lousada', 20);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Lousada', 'Gondomar', 20);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Gondomar', 'Maia', 20);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Maia', 'Gondomar', 20);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Gondomar', 'Marco de Canaveses', 30);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Marco de Canaveses', 'Gondomar', 30);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Gondomar', 'Matosinhos', 20);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Matosinhos', 'Gondomar', 20);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Gondomar', 'Paços de Ferreira', 20);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Paços de Ferreira', 'Gondomar', 20);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Gondomar', 'Paredes', 10);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Paredes', 'Gondomar', 10);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Gondomar', 'Penafiel', 20);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Penafiel', 'Gondomar', 20);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Gondomar', 'Porto', 10);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Porto', 'Gondomar', 10);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Gondomar', 'Póvoa de Varzim', 40);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Póvoa de Varzim', 'Gondomar', 40);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Gondomar', 'Santo Tirso', 30);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Santo Tirso', 'Gondomar', 30);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Gondomar', 'Trofa', 30);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Trofa', 'Gondomar', 30);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Gondomar', 'Valongo', 10);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Valongo', 'Gondomar', 10);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Gondomar', 'Vila do Conde', 30);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Vila do Conde', 'Gondomar', 30);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Gondomar', 'Vila Nova de Gaia', 10);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Vila Nova de Gaia', 'Gondomar', 10);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Lousada', 'Maia', 40);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Maia', 'Lousada', 40);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Lousada', 'Marco de Canaveses', 30);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Marco de Canaveses', 'Lousada', 30);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Lousada', 'Matosinhos', 40);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Matosinhos', 'Lousada', 40);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Lousada', 'Paços de Ferreira', 10);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Paços de Ferreira', 'Lousada', 10);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Lousada', 'Paredes', 10);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Paredes', 'Lousada', 10);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Lousada', 'Penafiel', 20);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Penafiel', 'Lousada', 20);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Lousada', 'Porto', 30);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Porto', 'Lousada', 30);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Lousada', 'Póvoa de Varzim', 30);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Póvoa de Varzim', 'Lousada', 30);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Lousada', 'Santo Tirso', 20);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Santo Tirso', 'Lousada', 20);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Lousada', 'Trofa', 30);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Trofa', 'Lousada', 30);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Lousada', 'Valongo', 20);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Valongo', 'Lousada', 20);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Lousada', 'Vila do Conde', 40);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Vila do Conde', 'Lousada', 40);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Lousada', 'Vila Nova de Gaia', 30);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Vila Nova de Gaia', 'Lousada', 30);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Maia', 'Marco de Canaveses', 50);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Marco de Canaveses', 'Maia', 50);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Maia', 'Matosinhos', 10);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Matosinhos', 'Maia', 10);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Maia', 'Paços de Ferreira', 30);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Paços de Ferreira', 'Maia', 30);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Maia', 'Paredes', 30);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Paredes', 'Maia', 30);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Maia', 'Penafiel', 40);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Penafiel', 'Maia', 40);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Maia', 'Porto', 10);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Porto', 'Maia', 10);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Maia', 'Póvoa de Varzim', 20);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Póvoa de Varzim', 'Maia', 20);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Maia', 'Santo Tirso', 20);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Santo Tirso', 'Maia', 20);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Maia', 'Trofa', 10);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Trofa', 'Maia', 10);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Maia', 'Valongo', 20);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Valongo', 'Maia', 20);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Maia', 'Vila do Conde', 10);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Vila do Conde', 'Maia', 10);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Maia', 'Vila Nova de Gaia', 20);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Vila Nova de Gaia', 'Maia', 20);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Marco de Canaveses', 'Matosinhos', 50);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Matosinhos', 'Marco de Canaveses', 50);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Marco de Canaveses', 'Paços de Ferreira', 30);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Paços de Ferreira', 'Marco de Canaveses', 30);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Marco de Canaveses', 'Paredes', 20);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Paredes', 'Marco de Canaveses', 20);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Marco de Canaveses', 'Penafiel', 10);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Penafiel', 'Marco de Canaveses', 10);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Marco de Canaveses', 'Porto', 40);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Porto', 'Marco de Canaveses', 40);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Marco de Canaveses', 'Póvoa de Varzim', 50);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Póvoa de Varzim', 'Marco de Canaveses', 50);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Marco de Canaveses', 'Santo Tirso', 40);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Santo Tirso', 'Marco de Canaveses', 40);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Marco de Canaveses', 'Trofa', 50);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Trofa', 'Marco de Canaveses', 50);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Marco de Canaveses', 'Valongo', 30);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Valongo', 'Marco de Canaveses', 30);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Marco de Canaveses', 'Vila do Conde', 60);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Vila do Conde', 'Marco de Canaveses', 60);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Marco de Canaveses', 'Vila Nova de Gaia', 40);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Vila Nova de Gaia', 'Marco de Canaveses', 40);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Matosinhos', 'Paços de Ferreira', 40);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Paços de Ferreira', 'Matosinhos', 40);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Matosinhos', 'Paredes', 30);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Paredes', 'Matosinhos', 30);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Matosinhos', 'Penafiel', 40);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Penafiel', 'Matosinhos', 40);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Matosinhos', 'Porto', 10);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Porto', 'Matosinhos', 10);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Matosinhos', 'Póvoa de Varzim', 30);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Póvoa de Varzim', 'Matosinhos', 30);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Matosinhos', 'Santo Tirso', 30);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Santo Tirso', 'Matosinhos', 30);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Matosinhos', 'Trofa', 20);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Trofa', 'Matosinhos', 20);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Matosinhos', 'Valongo', 20);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Valongo', 'Matosinhos', 20);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Matosinhos', 'Vila do Conde', 20);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Vila do Conde', 'Matosinhos', 20);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Matosinhos', 'Vila Nova de Gaia', 20);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Vila Nova de Gaia', 'Matosinhos', 20);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Paços de Ferreira', 'Paredes', 10);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Paredes', 'Paços de Ferreira', 10);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Paços de Ferreira', 'Penafiel', 20);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Penafiel', 'Paços de Ferreira', 20);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Paços de Ferreira', 'Porto', 30);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Porto', 'Paços de Ferreira', 30);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Paços de Ferreira', 'Póvoa de Varzim', 20);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Póvoa de Varzim', 'Paços de Ferreira', 20);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Paços de Ferreira', 'Santo Tirso', 10);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Santo Tirso', 'Paços de Ferreira', 10);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Paços de Ferreira', 'Trofa', 20);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Trofa', 'Paços de Ferreira', 20);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Paços de Ferreira', 'Valongo', 20);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Valongo', 'Paços de Ferreira', 20);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Paços de Ferreira', 'Vila do Conde', 30);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Vila do Conde', 'Paços de Ferreira', 30);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Paços de Ferreira', 'Vila Nova de Gaia', 30);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Vila Nova de Gaia', 'Paços de Ferreira', 30);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Paredes', 'Penafiel', 10);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Penafiel', 'Paredes', 10);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Paredes', 'Porto', 20);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Porto', 'Paredes', 20);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Paredes', 'Póvoa de Varzim', 30);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Póvoa de Varzim', 'Paredes', 30);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Paredes', 'Santo Tirso', 20);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Santo Tirso', 'Paredes', 20);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Paredes', 'Trofa', 30);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Trofa', 'Paredes', 30);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Paredes', 'Valongo', 10);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Valongo', 'Paredes', 10);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Paredes', 'Vila do Conde', 40);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Vila do Conde', 'Paredes', 40);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Paredes', 'Vila Nova de Gaia', 20);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Vila Nova de Gaia', 'Paredes', 20);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Penafiel', 'Porto', 30);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Porto', 'Penafiel', 30);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Penafiel', 'Póvoa de Varzim', 40);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Póvoa de Varzim', 'Penafiel', 40);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Penafiel', 'Santo Tirso', 30);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Santo Tirso', 'Penafiel', 30);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Penafiel', 'Trofa', 40);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Trofa', 'Penafiel', 40);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Penafiel', 'Valongo', 20);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Valongo', 'Penafiel', 20);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Penafiel', 'Vila do Conde', 50);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Vila do Conde', 'Penafiel', 50);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Penafiel', 'Vila Nova de Gaia', 30);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Vila Nova de Gaia', 'Penafiel', 30);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Porto', 'Póvoa de Varzim', 30);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Póvoa de Varzim', 'Porto', 30);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Porto', 'Santo Tirso', 30);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Santo Tirso', 'Porto', 30);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Porto', 'Trofa', 20);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Trofa', 'Porto', 20);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Porto', 'Valongo', 10);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Valongo', 'Porto', 10);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Porto', 'Vila do Conde', 20);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Vila do Conde', 'Porto', 20);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Porto', 'Vila Nova de Gaia', 10);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Vila Nova de Gaia', 'Porto', 10);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Póvoa de Varzim', 'Santo Tirso', 10);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Santo Tirso', 'Póvoa de Varzim', 10);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Póvoa de Varzim', 'Trofa', 10);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Trofa', 'Póvoa de Varzim', 10);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Póvoa de Varzim', 'Valongo', 40);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Valongo', 'Póvoa de Varzim', 40);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Póvoa de Varzim', 'Vila do Conde', 10);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Vila do Conde', 'Póvoa de Varzim', 10);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Póvoa de Varzim', 'Vila Nova de Gaia', 40);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Vila Nova de Gaia', 'Póvoa de Varzim', 40);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Santo Tirso', 'Trofa', 10);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Trofa', 'Santo Tirso', 10);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Santo Tirso', 'Valongo', 30);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Valongo', 'Santo Tirso', 30);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Santo Tirso', 'Vila do Conde', 20);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Vila do Conde', 'Santo Tirso', 20);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Santo Tirso', 'Vila Nova de Gaia', 40);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Vila Nova de Gaia', 'Santo Tirso', 40);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Trofa', 'Valongo', 30);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Valongo', 'Trofa', 30);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Trofa', 'Vila do Conde', 10);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Vila do Conde', 'Trofa', 10);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Trofa', 'Vila Nova de Gaia', 30);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Vila Nova de Gaia', 'Trofa', 30);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Valongo', 'Vila do Conde', 30);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Vila do Conde', 'Valongo', 30);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Valongo', 'Vila Nova de Gaia', 20);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Vila Nova de Gaia', 'Valongo', 20);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Vila do Conde', 'Vila Nova de Gaia', 30);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Vila Nova de Gaia', 'Vila do Conde', 30);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Amarante', 'Amarante', 0);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Baião', 'Baião', 0);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Felgueiras', 'Felgueiras', 0);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Gondomar', 'Gondomar', 0);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Lousada', 'Lousada', 0);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Maia', 'Maia', 0);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Marco de Canaveses', 'Marco de Canaveses', 0);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Matosinhos', 'Matosinhos', 0);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Paços de Ferreira', 'Paços de Ferreira', 0);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Paredes', 'Paredes', 0);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Penafiel', 'Penafiel', 0);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Porto', 'Porto', 0);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Póvoa de Varzim', 'Póvoa de Varzim', 0);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Santo Tirso', 'Santo Tirso', 0);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Trofa', 'Trofa', 0);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Valongo', 'Valongo', 0);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Vila do Conde', 'Vila do Conde', 0);
INSERT INTO distances_Porto (origin, destiny, distance) VALUES ('Vila Nova de Gaia', 'Vila Nova de Gaia', 0);

/************
   DISTANCES_DISTRICTS populate
************/

INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Viana do Castelo', 'Viana do Castelo', 0);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Viana do Castelo', 'Braga', 45);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Viana do Castelo', 'Vila Real', 90);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Viana do Castelo', 'Bragança', 135);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Viana do Castelo', 'Porto', 90);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Viana do Castelo', 'Aveiro', 135);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Viana do Castelo', 'Viseu', 135);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Viana do Castelo', 'Guarda', 180);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Viana do Castelo', 'Coimbra', 180);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Viana do Castelo', 'Castelo Branco', 180);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Viana do Castelo', 'Leiria', 225);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Viana do Castelo', 'Santarém', 225);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Viana do Castelo', 'Lisboa', 270);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Viana do Castelo', 'Portalegre', 225);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Viana do Castelo', 'Évora', 270);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Viana do Castelo', 'Setúbal', 315);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Viana do Castelo', 'Beja', 315);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Viana do Castelo', 'Faro', 360);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Viana do Castelo', 'Açores', 160);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Viana do Castelo', 'Madeira', 160);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Braga', 'Viana do Castelo', 45);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Braga', 'Braga', 0);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Braga', 'Vila Real', 45);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Braga', 'Bragança', 90);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Braga', 'Porto', 45);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Braga', 'Aveiro', 90);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Braga', 'Viseu', 90);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Braga', 'Guarda', 135);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Braga', 'Coimbra', 135);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Braga', 'Castelo Branco', 135);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Braga', 'Leiria', 180);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Braga', 'Santarém', 180);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Braga', 'Lisboa', 225);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Braga', 'Portalegre', 180);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Braga', 'Évora', 225);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Braga', 'Setúbal', 270);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Braga', 'Beja', 270);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Braga', 'Faro', 315);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Braga', 'Açores', 160);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Braga', 'Madeira', 160);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Vila Real', 'Viana do Castelo', 90);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Vila Real', 'Braga', 45);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Vila Real', 'Vila Real', 0);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Vila Real', 'Bragança', 45);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Vila Real', 'Porto', 45);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Vila Real', 'Aveiro', 90);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Vila Real', 'Viseu', 45);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Vila Real', 'Guarda', 90);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Vila Real', 'Coimbra', 90);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Vila Real', 'Castelo Branco', 90);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Vila Real', 'Leiria', 135);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Vila Real', 'Santarém', 135);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Vila Real', 'Lisboa', 180);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Vila Real', 'Portalegre', 135);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Vila Real', 'Évora', 180);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Vila Real', 'Setúbal', 225);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Vila Real', 'Beja', 225);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Vila Real', 'Faro', 270);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Vila Real', 'Açores', 160);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Vila Real', 'Madeira', 160);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Bragança', 'Viana do Castelo', 135);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Bragança', 'Braga', 90);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Bragança', 'Vila Real', 45);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Bragança', 'Bragança', 0);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Bragança', 'Porto', 90);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Bragança', 'Aveiro', 135);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Bragança', 'Viseu', 90);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Bragança', 'Guarda', 45);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Bragança', 'Coimbra', 135);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Bragança', 'Castelo Branco', 90);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Bragança', 'Leiria', 180);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Bragança', 'Santarém', 135);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Bragança', 'Lisboa', 180);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Bragança', 'Portalegre', 135);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Bragança', 'Évora', 180);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Bragança', 'Setúbal', 225);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Bragança', 'Beja', 225);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Bragança', 'Faro', 270);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Bragança', 'Açores', 160);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Bragança', 'Madeira', 160);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Porto', 'Viana do Castelo', 90);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Porto', 'Braga', 45);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Porto', 'Vila Real', 45);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Porto', 'Bragança', 90);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Porto', 'Porto', 0);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Porto', 'Aveiro', 45);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Porto', 'Viseu', 45);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Porto', 'Guarda', 90);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Porto', 'Coimbra', 90);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Porto', 'Castelo Branco', 90);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Porto', 'Leiria', 135);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Porto', 'Santarém', 135);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Porto', 'Lisboa', 180);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Porto', 'Portalegre', 135);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Porto', 'Évora', 180);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Porto', 'Setúbal', 225);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Porto', 'Beja', 225);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Porto', 'Faro', 270);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Porto', 'Açores', 160);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Porto', 'Madeira', 160);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Aveiro', 'Viana do Castelo', 135);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Aveiro', 'Braga', 90);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Aveiro', 'Vila Real', 90);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Aveiro', 'Bragança', 135);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Aveiro', 'Porto', 45);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Aveiro', 'Aveiro', 0);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Aveiro', 'Viseu', 45);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Aveiro', 'Guarda', 90);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Aveiro', 'Coimbra', 45);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Aveiro', 'Castelo Branco', 90);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Aveiro', 'Leiria', 90);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Aveiro', 'Santarém', 135);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Aveiro', 'Lisboa', 135);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Aveiro', 'Portalegre', 135);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Aveiro', 'Évora', 180);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Aveiro', 'Setúbal', 180);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Aveiro', 'Beja', 225);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Aveiro', 'Faro', 270);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Aveiro', 'Açores', 160);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Aveiro', 'Madeira', 160);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Viseu', 'Viana do Castelo', 135);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Viseu', 'Braga', 90);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Viseu', 'Vila Real', 45);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Viseu', 'Bragança', 90);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Viseu', 'Porto', 45);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Viseu', 'Aveiro', 45);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Viseu', 'Viseu', 0);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Viseu', 'Guarda', 45);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Viseu', 'Coimbra', 45);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Viseu', 'Castelo Branco', 45);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Viseu', 'Leiria', 90);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Viseu', 'Santarém', 90);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Viseu', 'Lisboa', 135);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Viseu', 'Portalegre', 90);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Viseu', 'Évora', 135);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Viseu', 'Setúbal', 180);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Viseu', 'Beja', 180);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Viseu', 'Faro', 225);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Viseu', 'Açores', 160);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Viseu', 'Madeira', 160);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Guarda', 'Viana do Castelo', 180);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Guarda', 'Braga', 135);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Guarda', 'Vila Real', 90);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Guarda', 'Bragança', 45);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Guarda', 'Porto', 90);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Guarda', 'Aveiro', 90);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Guarda', 'Viseu', 45);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Guarda', 'Guarda', 0);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Guarda', 'Coimbra', 90);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Guarda', 'Castelo Branco', 45);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Guarda', 'Leiria', 135);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Guarda', 'Santarém', 90);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Guarda', 'Lisboa', 135);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Guarda', 'Portalegre', 90);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Guarda', 'Évora', 135);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Guarda', 'Setúbal', 180);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Guarda', 'Beja', 180);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Guarda', 'Faro', 225);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Guarda', 'Açores', 160);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Guarda', 'Madeira', 160);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Coimbra', 'Viana do Castelo', 180);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Coimbra', 'Braga', 135);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Coimbra', 'Vila Real', 90);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Coimbra', 'Bragança', 135);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Coimbra', 'Porto', 90);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Coimbra', 'Aveiro', 45);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Coimbra', 'Viseu', 45);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Coimbra', 'Guarda', 90);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Coimbra', 'Coimbra', 0);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Coimbra', 'Castelo Branco', 45);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Coimbra', 'Leiria', 45);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Coimbra', 'Santarém', 90);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Coimbra', 'Lisboa', 90);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Coimbra', 'Portalegre', 90);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Coimbra', 'Évora', 135);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Coimbra', 'Setúbal', 135);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Coimbra', 'Beja', 180);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Coimbra', 'Faro', 225);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Coimbra', 'Açores', 160);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Coimbra', 'Madeira', 160);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Castelo Branco', 'Viana do Castelo', 180);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Castelo Branco', 'Braga', 135);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Castelo Branco', 'Vila Real', 90);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Castelo Branco', 'Bragança', 90);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Castelo Branco', 'Porto', 90);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Castelo Branco', 'Aveiro', 90);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Castelo Branco', 'Viseu', 45);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Castelo Branco', 'Guarda', 45);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Castelo Branco', 'Coimbra', 45);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Castelo Branco', 'Castelo Branco', 0);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Castelo Branco', 'Leiria', 90);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Castelo Branco', 'Santarém', 45);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Castelo Branco', 'Lisboa', 90);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Castelo Branco', 'Portalegre', 45);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Castelo Branco', 'Évora', 90);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Castelo Branco', 'Setúbal', 135);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Castelo Branco', 'Beja', 135);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Castelo Branco', 'Faro', 180);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Castelo Branco', 'Açores', 160);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Castelo Branco', 'Madeira', 160);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Leiria', 'Viana do Castelo', 225);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Leiria', 'Braga', 180);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Leiria', 'Vila Real', 135);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Leiria', 'Bragança', 180);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Leiria', 'Porto', 135);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Leiria', 'Aveiro', 90);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Leiria', 'Viseu', 90);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Leiria', 'Guarda', 135);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Leiria', 'Coimbra', 45);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Leiria', 'Castelo Branco', 90);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Leiria', 'Leiria', 0);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Leiria', 'Santarém', 45);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Leiria', 'Lisboa', 45);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Leiria', 'Portalegre', 90);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Leiria', 'Évora', 135);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Leiria', 'Setúbal', 90);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Leiria', 'Beja', 135);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Leiria', 'Faro', 180);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Leiria', 'Açores', 160);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Leiria', 'Madeira', 160);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Santarém', 'Viana do Castelo', 225);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Santarém', 'Braga', 180);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Santarém', 'Vila Real', 135);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Santarém', 'Bragança', 135);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Santarém', 'Porto', 135);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Santarém', 'Aveiro', 135);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Santarém', 'Viseu', 90);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Santarém', 'Guarda', 90);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Santarém', 'Coimbra', 90);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Santarém', 'Castelo Branco', 45);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Santarém', 'Leiria', 45);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Santarém', 'Santarém', 0);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Santarém', 'Lisboa', 45);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Santarém', 'Portalegre', 45);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Santarém', 'Évora', 90);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Santarém', 'Setúbal', 90);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Santarém', 'Beja', 135);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Santarém', 'Faro', 180);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Santarém', 'Açores', 160);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Santarém', 'Madeira', 160);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Lisboa', 'Viana do Castelo', 270);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Lisboa', 'Braga', 225);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Lisboa', 'Vila Real', 180);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Lisboa', 'Bragança', 180);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Lisboa', 'Porto', 180);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Lisboa', 'Aveiro', 135);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Lisboa', 'Viseu', 135);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Lisboa', 'Guarda', 135);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Lisboa', 'Coimbra', 90);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Lisboa', 'Castelo Branco', 90);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Lisboa', 'Leiria', 45);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Lisboa', 'Santarém', 45);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Lisboa', 'Lisboa', 0);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Lisboa', 'Portalegre', 90);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Lisboa', 'Évora', 90);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Lisboa', 'Setúbal', 45);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Lisboa', 'Beja', 90);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Lisboa', 'Faro', 135);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Lisboa', 'Açores', 160);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Lisboa', 'Madeira', 160);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Portalegre', 'Viana do Castelo', 225);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Portalegre', 'Braga', 180);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Portalegre', 'Vila Real', 135);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Portalegre', 'Bragança', 135);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Portalegre', 'Porto', 135);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Portalegre', 'Aveiro', 135);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Portalegre', 'Viseu', 90);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Portalegre', 'Guarda', 90);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Portalegre', 'Coimbra', 90);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Portalegre', 'Castelo Branco', 45);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Portalegre', 'Leiria', 90);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Portalegre', 'Santarém', 45);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Portalegre', 'Lisboa', 90);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Portalegre', 'Portalegre', 0);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Portalegre', 'Évora', 45);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Portalegre', 'Setúbal', 90);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Portalegre', 'Beja', 90);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Portalegre', 'Faro', 135);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Portalegre', 'Açores', 160);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Portalegre', 'Madeira', 160);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Évora', 'Viana do Castelo', 270);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Évora', 'Braga', 225);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Évora', 'Vila Real', 180);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Évora', 'Bragança', 180);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Évora', 'Porto', 180);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Évora', 'Aveiro', 180);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Évora', 'Viseu', 135);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Évora', 'Guarda', 135);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Évora', 'Coimbra', 135);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Évora', 'Castelo Branco', 90);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Évora', 'Leiria', 135);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Évora', 'Santarém', 90);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Évora', 'Lisboa', 90);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Évora', 'Portalegre', 45);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Évora', 'Évora', 0);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Évora', 'Setúbal', 45);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Évora', 'Beja', 45);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Évora', 'Faro', 90);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Évora', 'Açores', 160);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Évora', 'Madeira', 160);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Setúbal', 'Viana do Castelo', 315);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Setúbal', 'Braga', 270);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Setúbal', 'Vila Real', 225);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Setúbal', 'Bragança', 225);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Setúbal', 'Porto', 225);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Setúbal', 'Aveiro', 180);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Setúbal', 'Viseu', 180);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Setúbal', 'Guarda', 180);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Setúbal', 'Coimbra', 135);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Setúbal', 'Castelo Branco', 135);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Setúbal', 'Leiria', 90);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Setúbal', 'Santarém', 90);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Setúbal', 'Lisboa', 45);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Setúbal', 'Portalegre', 90);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Setúbal', 'Évora', 45);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Setúbal', 'Setúbal', 0);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Setúbal', 'Beja', 45);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Setúbal', 'Faro', 90);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Setúbal', 'Açores', 160);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Setúbal', 'Madeira', 160);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Beja', 'Viana do Castelo', 315);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Beja', 'Braga', 270);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Beja', 'Vila Real', 225);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Beja', 'Bragança', 225);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Beja', 'Porto', 225);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Beja', 'Aveiro', 225);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Beja', 'Viseu', 180);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Beja', 'Guarda', 180);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Beja', 'Coimbra', 180);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Beja', 'Castelo Branco', 135);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Beja', 'Leiria', 135);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Beja', 'Santarém', 135);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Beja', 'Lisboa', 90);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Beja', 'Portalegre', 90);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Beja', 'Évora', 45);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Beja', 'Setúbal', 45);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Beja', 'Beja', 0);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Beja', 'Faro', 45);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Beja', 'Açores', 160);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Beja', 'Madeira', 160);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Faro', 'Viana do Castelo', 360);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Faro', 'Braga', 315);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Faro', 'Vila Real', 270);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Faro', 'Bragança', 270);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Faro', 'Porto', 270);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Faro', 'Aveiro', 270);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Faro', 'Viseu', 225);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Faro', 'Guarda', 225);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Faro', 'Coimbra', 225);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Faro', 'Castelo Branco', 180);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Faro', 'Leiria', 180);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Faro', 'Santarém', 180);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Faro', 'Lisboa', 135);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Faro', 'Portalegre', 135);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Faro', 'Évora', 90);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Faro', 'Setúbal', 90);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Faro', 'Beja', 45);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Faro', 'Faro', 0);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Faro', 'Açores', 160);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Faro', 'Madeira', 160);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Açores', 'Viana do Castelo', 160);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Açores', 'Braga', 160);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Açores', 'Vila Real', 160);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Açores', 'Bragança', 160);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Açores', 'Porto', 160);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Açores', 'Aveiro', 160);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Açores', 'Viseu', 160);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Açores', 'Guarda', 160);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Açores', 'Coimbra', 160);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Açores', 'Castelo Branco', 160);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Açores', 'Leiria', 160);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Açores', 'Santarém', 160);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Açores', 'Lisboa', 160);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Açores', 'Portalegre', 160);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Açores', 'Évora', 160);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Açores', 'Setúbal', 160);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Açores', 'Beja', 160);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Açores', 'Faro', 160);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Açores', 'Açores', 0);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Açores', 'Madeira', 70);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Madeira', 'Viana do Castelo', 160);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Madeira', 'Braga', 160);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Madeira', 'Vila Real', 160);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Madeira', 'Bragança', 160);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Madeira', 'Porto', 160);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Madeira', 'Aveiro', 160);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Madeira', 'Viseu', 160);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Madeira', 'Guarda', 160);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Madeira', 'Coimbra', 160);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Madeira', 'Castelo Branco', 160);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Madeira', 'Leiria', 160);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Madeira', 'Santarém', 160);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Madeira', 'Lisboa', 160);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Madeira', 'Portalegre', 160);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Madeira', 'Évora', 160);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Madeira', 'Setúbal', 160);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Madeira', 'Beja', 160);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Madeira', 'Faro', 160);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Madeira', 'Açores', 70);
INSERT INTO distances_Districts (origin, destiny, distance) VALUES ('Madeira', 'Madeira', 0);